name: Deploy Lambda Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'services/**'
      - '.github/workflows/deploy-lambdas.yml'
      - 'shared/**'

env:
  PROJECT_NAME: "hobbes"
  PYTHON_VERSION: "3.12"

permissions:
  id-token: write    
  contents: read    # Required to checkout repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Update SSM Parameter
        run: |
          aws ssm put-parameter \
            --name "/Hobbes/database-url" \
            --value "${{ secrets.DATABASE_URL }}" \
            --type "SecureString" \
            --overwrite

      - name: Build webhook handler
        run: |
          mkdir -p dist/webhook-handler
          cp -r shared dist/webhook-handler/
          cp -r services/webhook/* dist/webhook-handler/
          cd dist/webhook-handler
          pip install -r ../../requirements.txt --target .
          zip -r ../webhook-handler.zip .
 
      - name: Build file processor
        run: |
          mkdir -p dist/file-processor
          cp -r shared dist/file-processor/
          cp -r services/file_processor/* dist/file-processor/
          cd dist/file-processor
          pip install -r ../../requirements.txt --target .
          zip -r ../file-processor.zip .

      - name: Build Analysis processor
        run: |
          mkdir -p dist/analysis-processor
          cp -r shared dist/analysis-processor/
          cp -r services/analysis_processor/* dist/analysis-processor/
          cd dist/analysis-processor
          pip install -r ../../requirements.txt --target .
          zip -r ../analysis-processor.zip .


      - name: Deploy webhook handler
        run: |
          aws lambda update-function-code \
            --function-name Hobbes-webhook-handler \
            --zip-file fileb://dist/webhook-handler.zip

      - name: Deploy file processor
        run: |
          aws lambda update-function-code \
            --function-name Hobbes-file-processor \
            --zip-file fileb://dist/file-processor.zip  

      - name: Deploy analysis processor
        run: |
          aws lambda update-function-code \
            --function-name Hobbes-analysis-processor \
            --zip-file fileb://dist/analysis-processor.zip  